name: Update wakatime stats

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "5 0 * * *"

jobs:
  build:
    name: Update-waka-stats
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md
      GIST_ID: 976cbecf83f29f44732391efd9fbccec
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT
